Model manager
webgme/ui-components pull request #3
Opened 2018-04-17 17:17 UTC by kecso

This simple visualizer allows easy management for models inside a single webgme project.
The visualizer is mainly intended for domain-specific use as it requires proper configuration in the
knowledge of the domain.
Design studios could leverage its easy access.

2018-04-18 14:33 UTC, pmeijer requested changes
I have some comments/questions.
Btw why not having a dedicated repo? That way it can show up on webgme.org

2018-04-18 14:33 UTC, pmeijer commented on package.json
> +    "webgme": "^2.25.0"
webgme should be in peerDependencies

2018-04-18 14:33 UTC, pmeijer commented on README.md
> +        "container": "pathOfTheContainer",
Is the root default here?

2018-04-18 14:33 UTC, pmeijer commented on README.md
> +        "types": ['componentName','otherComponentName']
It looks like the part-browser follows this as well - is that the case?

2018-04-18 14:33 UTC, pmeijer commented on src/visualizers/widgets/ModelManager/ModelManagerWidget.js
> +        BASE_WIDGET_FRAME = '<div class="col-sm-12">\n' +
For future reference you can use the new string templates, using `, for multi-line strings.

2018-04-18 14:33 UTC, pmeijer commented on src/visualizers/widgets/ModelManager/ModelManagerWidget.js
> +        SINGLE_CREATE_BUTTON = '<button id="createBtn" type="button" class="btn btn-danger">Create a new</button>',
This should probably not be danger (red).

2018-04-18 14:33 UTC, pmeijer commented on src/visualizers/widgets/ModelManager/ModelManagerWidget.js
> +                    self._config.inFault = true;
If one is missing, can it still proceed?

2018-04-18 16:34 UTC, kecso commented on README.md
> +        "container": "pathOfTheContainer",
no, right now there is no default anywhere and the container of choice has to exsist for the visualizer to work

2018-04-18 16:35 UTC, kecso commented on README.md
> +        "types": ['componentName','otherComponentName']
no, that is just a coincidence of the picture.
this visualizer has nothing to do with the part browser though I believe a good configuration will match in that regard

2018-04-18 16:35 UTC, kecso commented on src/visualizers/widgets/ModelManager/ModelManagerWidget.js
> +        BASE_WIDGET_FRAME = '<div class="col-sm-12">\n' +
I'll change it

2018-04-18 16:36 UTC, kecso commented on src/visualizers/widgets/ModelManager/ModelManagerWidget.js
> +        SINGLE_CREATE_BUTTON = '<button id="createBtn" type="button" class="btn btn-danger">Create a new</button>',
changing it to default or something then

2018-04-18 16:37 UTC, kecso commented on src/visualizers/widgets/ModelManager/ModelManagerWidget.js
> +                    self._config.inFault = true;
right now not.
it is rigid in that sense, but I wanted it that way to make it more tailored for design studio use

2018-04-18 16:38 UTC, kecso commented
I thought having it as a 'generic' visualizer makes it more visible.
But you might be right (I think we need to advertise it anyhow as part of a design studio know how...)

2018-04-18 17:30 UTC, pmeijer commented on README.md
> +        "types": ['componentName','otherComponentName']
Why not hide the parts in the partbrowser then? Would be esp. nice if you're using the root-node as the container to not show all the parts.

2018-04-18 17:45 UTC, pmeijer commented
Testing it now and it throws an exception if there is no config defined.
I'd suggest using the rootNode as default container and if no types are defined just display all.
```
q.js:349 Uncaught TypeError: Cannot read property 'length' of undefined
    at ModelManagerWidget.js:76
    at q.js:2243
    at runSingle (q.js:325)
    at MessagePort.flush (q.js:313)
```

2018-04-18 17:49 UTC, pmeijer commented on src/visualizers/widgets/ModelManager/ModelManagerWidget.js
> +                console.log('yeah, I am going to view :', model.path);
Left out logs

2018-04-18 17:50 UTC, pmeijer commented
Would be nice if it filtered the existing children based on the provided types

2018-04-18 17:53 UTC, pmeijer commented
Also consider pulling the "Create new.." and "Import buttons" to the right or left.

2018-04-19 13:49 UTC, pmeijer approved these changes

2018-04-19 13:49 UTC, merged